### ISSUE TITLE
WorkflowId with spaces or ampersands (or any char that needs to be url encoded it seems) causes 404 on exec view

### ISSUE THREAD

**Issue by tsurdilo** [temporalio/temporalite#117]
<img width="1703" alt="Screen Shot 2022-08-08 at 12 16 36 PM" src="https://user-images.githubusercontent.com/119422/183464686-63d17829-a24a-41fb-8b44-ea286ee006af.png">

<img width="1657" alt="Screen Shot 2022-08-08 at 12 16 41 PM" src="https://user-images.githubusercontent.com/119422/183464712-291ae553-c0b4-41dc-bc31-af6f57de3d52.png">

Note, this was tested with latest temporalite, just fyi

**Comment by hrishikesh2306** [comment]
> Can this be expedited if possible? Facing lot of issues during development.

Is there any workaround that I can use till this is fixed?

**Comment by hrishikesh2306** [comment]
Installed temporalite using the default @latest command. Change doesn't seem to be reflected. I see that the change is merged into main. Do I need to wait for creation of some build, etc.?
