### ISSUE TITLE
Add detach option

### ISSUE THREAD

**Issue by lorensr** [temporalio/temporalite#139]
**Is your feature request related to a problem? Please describe.**

In order to not see output, I have to add `> /dev/null 2>&1 &` like:

`temporalite start --namespace default --ephemeral > /dev/null 2>&1 &`

**Describe the solution you'd like**

Something like docker-compose's -d flag:

```
  -d, --detach                    Detached mode: Run containers in the background
```

**Comment by cretz** [comment]
As with our production Temporal server and most binaries out there, we should leave stdio redirection and backgrounding to the caller IMO. Docker compose's option is not a common one among binaries like this.

**Comment by jlegrone** [comment]
I agree with @cretz on this one; docker-compose also ships a bunch of subcommands like `ls` which are used for enumerating and managing those background processes. I'd prefer to avoid this complexity in Temporalite.

Closing for now, but I'm happy to reconsider if this ends up being a really popular community request.
