### ISSUE TITLE
Time skipping

### ISSUE THREAD

**Issue by cv65kr** [temporalio/temporalite#142]
**Is your feature request related to a problem? Please describe.**
In the Temporal test server based on Java there is functionality for skipping time. It's very useful for CI purposes.
```
The test framework provides a TestWorkflowEnvironment class which includes an in-memory implementation of the Temporal service that supports automatic time skipping. 
This allows you to easily test long-running Workflows in seconds, without having to change your Workflow code.
``` 

**Describe the solution you'd like**
Similar way like in Java, but generally in Java test server skipping is enabled by default. So there should be new endpoint for enabling/disabling.

**Comment by cretz** [comment]
This is an extreme undertaking. Temporalite is a thin API wrapper that just runs the _full_ Temporal server. The Temporal server does not support time skipping and it is not reasonable to incorporate it at this time.

But we put in the effort to make the Java time skipping server a simple binary you can run (see the GitHub releases area of sdk-java). Also if you're using TypeScript or Python, we have abstracted starting Temporalite and starting a time-skipping server using similar APIs that also automatically download both things for you.

Feel free to ask questions about time skipping servers or these APIs in Slack at https://temporal.io/slack or the forum at https://community.temporal.io.
