### ISSUE TITLE
Temporalite v0.2.0 fails to install

### ISSUE THREAD

**Issue by joelmarty** [temporalio/temporalite#147]
## Expected Behavior

Temporalite installs successfully using `go install`

## Actual Behavior

Installation fails with the following error:
```
go: github.com/temporalio/temporalite/cmd/temporalite@v0.2.0 (in github.com/temporalio/temporalite@v0.2.0):
	The go.mod file for the module providing named packages contains one or
	more replace directives. It must not contain directives that would cause
	it to be interpreted differently than if it were the main module.
```

## Steps to Reproduce the Problem

1. Run `go install github.com/temporalio/temporalite/cmd/temporalite@v0.2.0`
2. Installation fails with mentioned error

## Specifications

- Version: 0.2.0
- Platform: darwin-amd64

**Comment by cretz** [comment]
The recommended install approach has changed to use the binaries from the GitHub releases area due to this issue (or build and run yourself).

**Comment by joelmarty** [comment]
I guess this issue has become a documentation issue :)

**Comment by jlegrone** [comment]
Yep I would love for `go install` to work, but I'm afraid we're a bit stuck at the moment due to the fork of grpc-gateway. We'll update docs when this is resolved, but I will close this issue for now since installation instructions have been updated.

**Comment by deinspanjer** [comment]
@jlegrone please note that the readmes that are bundled with the 0.2.0 executables still reference the `go install` method.

It might also be useful to mention that by default, Mac OSX won't let you run the executable when downloaded. You need to hold down control and double click on the executable first to get a dialog that will let you accept the fact it isn't signed and known to be secure.  After that, the executable can be run from the command line as normal.
