### ISSUE TITLE
temporalite homebrew 

### ISSUE THREAD

**Issue by atileren** [temporalio/temporalite#179]
**Is your feature request related to a problem? Please describe.**
I think we need to give alternative ways for installation temporalite. There is an easy way to use temporalite binary like homebrew for mac users. is there any obstacle to it?

**Describe the solution you'd like**
We can integrate brew release mechanism with goreleaser in an autonomous way and people can install temporalite easily on their macs. 

**Describe alternatives you've considered**
I don't have alternative

**Additional context**
if it's acceptable I can work on it. Temporalio project has already homebrew repository. I can easily integrate with it in an autonomous way .

**Comment by robholland** [comment]
Temporalite is available via the `temporal start-dev`, part of the Temporal CLI which is installable via homebrew: https://github.com/temporalio/cli

**Comment by atileren** [comment]
thanks @robholland I didn't know I can use temporalite via temporal cli. But people might want use directly temporalite without temporal cli in this case home-brew good alternative for installation. 

Also there is a similar issue I hadn't noticed it when I opened that issue. You can close too
https://github.com/temporalio/temporalite/issues/106
