### ISSUE TITLE
Publish Temporalite on nixpkgs

### ISSUE THREAD

**Issue by schickling** [temporalio/temporalite#31]
It would be great if Temporalite was published on [nixpkgs](https://github.com/NixOS/nixpkgs) :)

**Comment by schickling** [comment]
FYI In the meanwhile I'm using this in a Nix flake:

```nix
{ fetchFromGitHub
, lib
, buildGo117Module
}:

buildGo117Module rec {
  pname = "temporalite";
  version = "1.14.1";

  src = fetchFromGitHub
    {
      owner = "DataDog";
      repo = pname;
      # TODO fix https://github.com/temporalio/ui-server/issues/80
      rev = "583fa90e84e6730c85add1ad781b52ba5caf9342";
      sha256 = "sha256-JuaE+KCQV1Os7qk4ZyO8g45Qn7Q3BMtsAPTOVYAxVKQ=";
    };

  # goPackagePath = "github.com/DataDog/temporalite";
  subPackages = [ "cmd/temporalite" ];

  vendorSha256 = null;

  buildFlags = "-mod=readonly";

  # don't run tests
  doCheck = false;
}
```

**Comment by kearfy** [comment]
Hi there, 

I've been working on a flake for the past day and got it working, but only up until release 1.15.1 (commit [0797d11e124e64b068be86566ef6577d80563c9c](https://github.com/DataDog/temporalite/commit/0797d11e124e64b068be86566ef6577d80563c9c))

In commit [0507fa8874f2107cf5a97202abf6c518759f1515](https://github.com/DataDog/temporalite/commit/0507fa8874f2107cf5a97202abf6c518759f1515) they have upgraded to go 1.18, and I suspect that that is the reason for the following error in the next series of commits while retrieving all the dependencies:

`go mod vendor: pattern all:generated/openapi: no matching files found`

I've already tried to run this in untested versions of nix aswell but can't get past this error for 1.16.x builds. Is anybody willing and able to help out with this problem?

This is the repository that I'm working in: [https://github.com/kearfy/temporalite-nix](https://github.com/kearfy/temporalite-nix)

**Comment by kearfy** [comment]
Hey, just wanted to let you all know that I got the latest version of temporalite working in my last commit. Still working out a way to store the vendorSha256 elsewhere but this does not seem to have a proper solution, unfortunately.

**Comment by sagikazarmark** [comment]
PR to nixpkgs: https://github.com/NixOS/nixpkgs/pull/197636

In the meantime, it's available from my NUR: https://github.com/sagikazarmark/nur-packages

**Comment by sagikazarmark** [comment]
Temporalite is in nixpkgs: https://search.nixos.org/packages?channel=unstable&from=0&size=50&sort=relevance&type=packages&query=temporalite
