### ISSUE TITLE
Temporalite fails to start when file persistence is configured in nonexistent directory

### ISSUE THREAD

**Issue by jlegrone** [temporalio/temporalite#55]
## Expected Behavior

Temporalite could create the directory first, then start writing to the database file.

## Actual Behavior

User sees an error message like

```
2022/04/04 18:57:43 error setting up schema: unable to create SQLite admin DB: unable to open database file: no such file or directory
```

The error text doesn't include the file path that is being opened, which makes understanding the issue a bit more difficult.

## Steps to Reproduce the Problem

1. `temporalite start -f some_dir_that_does_not_exist/foo.db`

## Specifications

- Version: `main`
- Platform: Any

**Comment by jlegrone** [comment]
I'm a bit concerned about automatically creating a new directory. If this was due to a typo, then workflows could be started right away in the new database and merging state between the old and new databases would be tricky.

A change to improve the error message would be very welcome however!

**Comment by rgooch** [comment]
@jlegrone Which OS did you run this on? I think this is similar to the problem I'm seeing on MacOS.
Using the default DB location:
`~/go/bin/temporalite start --namespace local
2022/08/01 09:12:37 error setting up schema: unable to create SQLite admin DB: unable to open database file: out of memory (14)`

Using a specified DB location where the parent directory does not exist:
`~/go/bin/temporalite start --namespace local -f ~/notthere/my.db
2022/08/01 09:12:00 error setting up schema: unable to create SQLite admin DB: unable to open database file: out of memory (14)`

**Comment by marchmallow** [comment]
@jlegrone I am trying temporalite for the first time and indeed hitting this just as I do (following the README steps):

```
% go install github.com/temporalio/temporalite/cmd/temporalite@latest
go: downloading github.com/temporalio/temporalite v0.0.0-20220801155940-a4b633da82bc
% temporalite start --namespace default
2022/08/02 13:46:14 error setting up schema: unable to create SQLite admin DB: unable to open database file: out of memory (14)
```

If instead I do `temporalite start --namespace default -f my_test.db` then it works

**Comment by jlegrone** [comment]
@marchmallow can you confirm that you get a more explicit error message now that #99 is merged?

**Comment by marchmallow** [comment]
> @marchmallow can you confirm that you get a more explicit error message now that #99 is merged?

@jlegrone yes now I see a meaningful error message:

```
% temporalite start --namespace default
2022/08/11 16:56:02 error setting up schema: stat /Users/max.gallo/Library/Application Support/temporalite/db: no such file or directory
```

So eg I created the dir and works:

```
% mkdir  /Users/max.gallo/Library/Application\ Support/temporalite/db -p
% temporalite start --namespace default
{"level":"info","ts":"2022-08-11T16:57:05.983+0100","msg":"Successfully saved cluster metadata.","component":"metadata-initializer","cluster-name":"active","logging-call-at":"fx.go:631"}
```

**Comment by longquanzheng** [comment]
> @jlegrone I am trying temporalite for the first time and indeed hitting this just as I do (following the README steps):
> 
> ```
> % go install github.com/temporalio/temporalite/cmd/temporalite@latest
> go: downloading github.com/temporalio/temporalite v0.0.0-20220801155940-a4b633da82bc
> % temporalite start --namespace default
> 2022/08/02 13:46:14 error setting up schema: unable to create SQLite admin DB: unable to open database file: out of memory (14)
> ```
> 
> If instead I do `temporalite start --namespace default -f my_test.db` then it works

Got the same error and this command works for me
