### ISSUE TITLE
Tag releases

### ISSUE THREAD

**Issue by cretz** [temporalio/temporalite#94]
**Is your feature request related to a problem? Please describe.**

It seems goreleaser is setup, but there are no tags to trigger releases to build binaries. Having downloadable binaries helps users of Temporalite who don't want to build. For my use case in particular, the Python SDK would love to download and run Temporalite instead of building it in CI.

**Describe the solution you'd like**

Tag releases. Granted I can't figure out what the best release numbering scheme would be considering this is also a Go library so must remain on semver, but it may make sense to align with server version.

(this is obviously non-urgent as building Temporalite is trivial)

**Comment by jlegrone** [comment]
I suppose we could use tagged releases that track the temporal server version, and then abuse the go module identifier a bit by updating the module name (eg. add a `/v2` suffix) if we need to make a breaking change to the go library.

Another idea I've considered is using exclusively pre-release versions with a suffix matching the temporal server version, eg. `X.X.X-1.17.2`. I'm not sure how nicely the latter would play with tooling like `go mod` or dependabot though.

**Comment by cretz** [comment]
> abuse the go module identifier a bit by updating the module name (eg. add a /v2 suffix) if we need to make a breaking change to the go library.

I think, with how Temporalite is used, we could make minor breaking changes without major semver bump. Major semver bumps in Go are rough and most libraries are 0.x or 1.x forever because of it (even with technically-semver-major compat breaks)

> Another idea I've considered [...]

I'll take any approach that gets us binaries.

I'd like to continue to not use tags so it doesn't affect go mod at all and instead use some kind of faux tag release branch to trigger the binary creator in CI, but GH I believe requires tags for releases and that's where you want to attach the binaries.

Maybe the best way is, at least while this is considered non-production, doing https://0ver.org/ (though I know that's kinda satire, in this case it wouldn't be). Basically just have Temporalite keep its own version unrelated to server (people can look at the `go.mod` file if they want to know server version) and tag as we feel like it, starting with 0.1.0 and incrementing that minor number indefinitely.

**Comment by jlegrone** [comment]
Hah, thanks for the link to 0ver.org. You know it's good when you can't tell if satire or not.

How about this: we start at `v0.1.0` and stay at `v0` until such a time as we decide to align with Temporal server version numbers or come up with a better idea. An eventual bump from `v0.X.X` to whatever the latest Temporal server version is can be handled gracefully.

In the mean time we can also add a `temporalite version` subcommand that spits out the Temporal server version so that people don't have to resort to cross-referencing the go.mod file at particular Temporalite releases.

**Comment by jlegrone** [comment]
> I'd like to continue to not use tags so it doesn't affect go mod at all

I think tagged releases would be nice for library users. This would also help dependabot and other similar tooling do its thing. Do you have any risks in mind with using git tags?

**Comment by cretz** [comment]
Nope, that's what I had in mind when creating the issue. My only original concern was it may be non-obvious which server it lines up with, but in retrospect that's not a big deal.

**Comment by jlegrone** [comment]
Done as of https://github.com/temporalio/temporalite/releases/tag/v0.1.0
